### PR TITLE
Set base URL differently in Bitbucket cloud

### LINKED ISSUE #3: Concurrency issue with bitbucket
On this file 
https://github.com/jfrog/froggit-go/blob/40ca96b66fb0aef79adf9d8814f40af7682b7552/vcsclient/bitbucketcloud.go#L23
We get the url via environment variable so if we need multiple bitbucket call in parallel, they might use a wrong value

### PR DESCRIPTION
**Pull request by yahavi**
Resolves #3 

Instead of setting the Bitbucket cloud base URL by an environment variable, set the URL after the creation of the client. This attitude should be thread safe.

### CODE REVIEW

File: vcsclient/bitbucketcloud.go [hunk 1]
```diff
@@ -16,21 +15,29 @@ import (
 
 type BitbucketCloudClient struct {
 	vcsInfo VcsInfo
+	url     *url.URL
```
Comment (cyrilc-pro) [inline vcsclient/bitbucketcloud.go:18]: Why a pointer?

File: vcsclient/bitbucketcloud.go [hunk 2]
```diff
@@ -16,21 +15,29 @@ import (
...
-	}
 	bitbucketClient := &BitbucketCloudClient{
 		vcsInfo: vcsInfo,
 	}
+	if vcsInfo.ApiEndpoint != "" {
+		url, err := url.Parse(vcsInfo.ApiEndpoint)
+		if err != nil {
+			return nil, err
+		}
+		bitbucketClient.url = url
```
Comment (cyrilc-pro) [inline vcsclient/bitbucketcloud.go:30]: If this value can be computed from `bitbucketClient.ApiEndpoint`, then I suggest we always compute it instead of "caching" the computation result.

Meaning, we should compute the URL in the `buildBitbucketCloudClient` function.

**Review by cyrilc-pro — APPROVED** [review]

File: vcsclient/bitbucketcloud.go (hunk 1 above)
Comment (yahavi) [reply vcsclient/bitbucketcloud.go:18]: To check if the value is initialized in `buildBitbucketCloudClient`: 
```go
if client.url != nil {
	bitbucketClient.SetApiBaseURL(*client.url)
}
```
Do you see any problem with that?

File: vcsclient/bitbucketcloud.go (hunk 2 above)
Comment (cyrilc-pro) [reply vcsclient/bitbucketcloud.go:30]: Just to avoid having in a struct a field whose value can be computed. A bit like having two fields 'age' and 'date of birth' for a 'person' type.
Anyway, your call.

File: vcsclient/bitbucketcloud.go (hunk 1 above)
Comment (cyrilc-pro) [reply vcsclient/bitbucketcloud.go:18]: No,OK, I get it. It makes sense if there's a default value in the bitbucket client library.
